import { test } from "../fixtures";
import type { Page } from "@playwright/test";
import * as fs from "node:fs";
import * as path from "node:path";

/** The figures in the in-app tutorial.
 *
 *  Checked in rather than generated at build time, and generated by a spec
 *  rather than cropped by hand.  design.md's own rule is that the document
 *  and the build may not drift silently, and a hand-made screenshot of an
 *  interface that has since moved on is exactly that drift -- in the one
 *  surface whose whole purpose is to describe the build.  Regenerating has
 *  to be one command, and this is it:
 *
 *    cd e2e && node_modules/.bin/playwright test --config shots.config.ts
 *
 *  Each crop is taken at twice the size it is shown, so it is pixel-exact
 *  on a Retina display and downsamples cleanly on an ordinary one.
 */

const OUT = path.join(
  process.cwd(), "..", "frontend", "src", "panes", "tutorial", "shots",
);

const THEMES = ["light", "dark"] as const;

async function dress(page: Page, theme: string) {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.evaluate((t) => {
    window.localStorage.setItem("nexttex.theme", t);
    for (const key of Object.keys(window.localStorage)) {
      if (key.startsWith("nexttex.widths.") || key.startsWith("nexttex.folded.")) {
        window.localStorage.removeItem(key);
      }
    }
  }, theme);
  await page.reload();
  await page.locator(".cm-editor").waitFor({ timeout: 30_000 });
  await page.waitForTimeout(1200);
}

/** One element, padded. */
async function shot(page: Page, name: string, theme: string, selector: string, pad = 0) {
  const box = await page.locator(selector).first().boundingBox();
  if (!box) return;
  fs.mkdirSync(OUT, { recursive: true });
  await page.screenshot({
    path: path.join(OUT, `${name}-${theme}.png`),
    clip: {
      x: Math.max(0, box.x - pad),
      y: Math.max(0, box.y - pad),
      width: box.width + pad * 2,
      height: box.height + pad * 2,
    },
  });
}

/** From the left edge of one element to the right edge of another, which is
 *  how a row of separate controls is cropped as the one thing it reads as. */
async function span(
  page: Page, name: string, theme: string,
  from: string, to: string, height: number, pad = 0,
) {
  const a = await page.locator(from).first().boundingBox();
  const b = await page.locator(to).first().boundingBox();
  if (!a || !b) return;
  fs.mkdirSync(OUT, { recursive: true });
  await page.screenshot({
    path: path.join(OUT, `${name}-${theme}.png`),
    clip: {
      x: Math.max(0, a.x - pad),
      y: Math.max(0, a.y - pad),
      width: b.x + b.width - a.x + pad * 2,
      height,
    },
  });
}

async function ask(page: Page, script: string, question: string) {
  const composer = page.locator("textarea");
  await composer.click();
  await composer.fill(`#script:${script}\n${question}`);
  await page.getByRole("button", { name: "Send" }).click();
}

test.setTimeout(300_000);

test("the figures the tutorial shows", async ({ app, project, tab }) => {
  // Two files open, so the tab strip has a visible empty run beside them,
  // which is the whole point of that figure.
  await tab.evaluate(
    async ({ base, token, id }) => {
      for (const name of ["chapters/results.tex", "chapters/theory.tex"]) {
        await fetch(`${base}/api/projects/${id}/file`, {
          method: "PUT",
          headers: { "content-type": "application/json", "x-nexttex-token": token },
          body: JSON.stringify({
            path: name, text: "\\section{A section}\nSome prose.\n",
            compile: false, create: true,
          }),
        });
      }
    },
    { base: app.base, token: app.token, id: project.id },
  );

  for (const theme of THEMES) {
    await dress(tab, theme);

    // The git card first: it is only there until somebody dismisses it, and
    // a reader who did has no way left to see what it was.
    await shot(tab, "git-card", theme, '[data-testid="git-setup"]');

    // Two tabs, so the empty run writing mode is reached by is visible.
    await tab.getByTestId("file-search-open").click();
    await tab.getByTestId("file-search").fill("results");
    await tab.locator('[role="tree"] [data-path="chapters/results.tex"]').click();
    await tab.getByTestId("file-search").fill("theory");
    await tab.locator('[role="tree"] [data-path="chapters/theory.tex"]').click();
    await tab.getByTestId("file-search").press("Escape");
    await tab.waitForTimeout(500);
    await span(tab, "tab-strip", theme, "[data-tab]", '[data-testid="tabs-blank"]', 34);

    // An edit chip, opened to its diff: what an agent edit looks like
    // before you have ever had one.
    await ask(tab, "edit", "Add a sentence about the method.");
    await tab.getByTestId("edit-chip").first().waitFor({ timeout: 20_000 });
    await tab.getByTestId("edit-chip").first().getByRole("button").first().click();
    await tab.waitForTimeout(500);
    await shot(tab, "edit-chip", theme, '[data-testid="edit-chip"]', 6);

    // The one card in the app where a mistaken click runs a command.
    await ask(tab, "permission", "Run the build once.");
    await tab.getByTestId("allow").waitFor({ timeout: 20_000 });
    await tab.waitForTimeout(700);
    await shot(tab, "permission-card", theme, '[data-testid="permission-card"]', 6);
    await tab.getByTestId("deny").click();
    await tab.waitForTimeout(400);

    // The buttons under the box, none of which carries a label.
    await span(tab, "composer-row", theme, '[data-testid="clear-chat"]', 'button:has-text("Send")', 34, 8);

    // A document that does not compile, with the drawer open and the
    // explanation above the list.  Last, because it dirties the project.
    //
    // Written through the API rather than typed.  An undefined control
    // sequence has to land *inside* the document body, and the caret in a
    // fresh project sits after \\end{document}, where LaTeX reads nothing --
    // so typing it produced no errors at all, three runs in a row.
    const breakIt = async (broken: boolean) => {
      await tab.evaluate(
        async ({ base, token, id, broken }) => {
          const url = `${base}/api/projects/${id}/file?path=main.tex`;
          const read = await fetch(url, {
            headers: { "x-nexttex-token": token },
          }).then((r) => r.json());
          const text = broken
            ? String(read.text).replace(
                "\\end{document}",
                "\\thisCommandDoesNotExist\n\\end{document}",
              )
            : String(read.text).replace("\\thisCommandDoesNotExist\n", "");
          await fetch(`${base}/api/projects/${id}/file`, {
            method: "PUT",
            headers: {
              "content-type": "application/json",
              "x-nexttex-token": token,
            },
            body: JSON.stringify({ path: "main.tex", text, compile: true }),
          });
        },
        { base: app.base, token: app.token, id: project.id, broken },
      );
    };

    await breakIt(true);
    await tab
      .locator(".cm-gutter-error")
      .first()
      .waitFor({ timeout: 60_000 })
      .catch(() => undefined);
    await tab.getByTestId("status").click();
    await tab.getByTestId("diagnostics").waitFor({ timeout: 15_000 });
    await tab.waitForTimeout(700);
    await shot(tab, "errors", theme, '[data-testid="diagnostics"]');

    // Put it back, so the second theme starts from a document that builds.
    await breakIt(false);
    await tab.waitForTimeout(1500);
  }
});
